In [13]:
import torch
import numpy as np

In [14]:
a_0 = torch.Tensor([1])
print(a_0)
print(a_0.size())

tensor([1.])
torch.Size([1])


In [15]:
a_0 = torch.Tensor([])
print(a_0)

tensor([])


In [16]:
for i in range(100):
    a_0 = np.append(a_0,i)
    
print(a_0)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
 18. 19. 20. 21. 22. 23. 24. 25. 26. 27. 28. 29. 30. 31. 32. 33. 34. 35.
 36. 37. 38. 39. 40. 41. 42. 43. 44. 45. 46. 47. 48. 49. 50. 51. 52. 53.
 54. 55. 56. 57. 58. 59. 60. 61. 62. 63. 64. 65. 66. 67. 68. 69. 70. 71.
 72. 73. 74. 75. 76. 77. 78. 79. 80. 81. 82. 83. 84. 85. 86. 87. 88. 89.
 90. 91. 92. 93. 94. 95. 96. 97. 98. 99.]


In [24]:
#授業内課題1
a_0 =torch.arange(100)
a_0

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
        36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53,
        54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71,
        72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89,
        90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [17]:
#授業内課題2
torch_array= torch.linspace(0,1,100)
print(torch_array)

tensor([0.0000, 0.0101, 0.0202, 0.0303, 0.0404, 0.0505, 0.0606, 0.0707, 0.0808,
        0.0909, 0.1010, 0.1111, 0.1212, 0.1313, 0.1414, 0.1515, 0.1616, 0.1717,
        0.1818, 0.1919, 0.2020, 0.2121, 0.2222, 0.2323, 0.2424, 0.2525, 0.2626,
        0.2727, 0.2828, 0.2929, 0.3030, 0.3131, 0.3232, 0.3333, 0.3434, 0.3535,
        0.3636, 0.3737, 0.3838, 0.3939, 0.4040, 0.4141, 0.4242, 0.4343, 0.4444,
        0.4545, 0.4646, 0.4747, 0.4848, 0.4949, 0.5051, 0.5152, 0.5253, 0.5354,
        0.5455, 0.5556, 0.5657, 0.5758, 0.5859, 0.5960, 0.6061, 0.6162, 0.6263,
        0.6364, 0.6465, 0.6566, 0.6667, 0.6768, 0.6869, 0.6970, 0.7071, 0.7172,
        0.7273, 0.7374, 0.7475, 0.7576, 0.7677, 0.7778, 0.7879, 0.7980, 0.8081,
        0.8182, 0.8283, 0.8384, 0.8485, 0.8586, 0.8687, 0.8788, 0.8889, 0.8990,
        0.9091, 0.9192, 0.9293, 0.9394, 0.9495, 0.9596, 0.9697, 0.9798, 0.9899,
        1.0000])


In [19]:
#授業内課題3
torch_array.view(100,1)

tensor([[0.0000],
        [0.0101],
        [0.0202],
        [0.0303],
        [0.0404],
        [0.0505],
        [0.0606],
        [0.0707],
        [0.0808],
        [0.0909],
        [0.1010],
        [0.1111],
        [0.1212],
        [0.1313],
        [0.1414],
        [0.1515],
        [0.1616],
        [0.1717],
        [0.1818],
        [0.1919],
        [0.2020],
        [0.2121],
        [0.2222],
        [0.2323],
        [0.2424],
        [0.2525],
        [0.2626],
        [0.2727],
        [0.2828],
        [0.2929],
        [0.3030],
        [0.3131],
        [0.3232],
        [0.3333],
        [0.3434],
        [0.3535],
        [0.3636],
        [0.3737],
        [0.3838],
        [0.3939],
        [0.4040],
        [0.4141],
        [0.4242],
        [0.4343],
        [0.4444],
        [0.4545],
        [0.4646],
        [0.4747],
        [0.4848],
        [0.4949],
        [0.5051],
        [0.5152],
        [0.5253],
        [0.5354],
        [0.5455],
        [0

In [22]:
#授業内課題4
torch_array =  torch.randn(100)
torch_array.view(100,1)

tensor([[ 1.5625e-02],
        [-2.3056e-02],
        [-4.1401e-01],
        [ 2.6228e-01],
        [ 2.1894e-01],
        [-5.8546e-01],
        [-6.3291e-01],
        [-3.7932e-01],
        [ 6.2812e-01],
        [ 2.2144e-01],
        [-1.1570e+00],
        [ 5.0288e-02],
        [ 1.1175e+00],
        [-4.1763e-01],
        [-1.8397e+00],
        [-2.9026e-01],
        [ 1.5733e+00],
        [-4.0157e-01],
        [ 1.2632e+00],
        [ 7.9719e-01],
        [-3.0151e-01],
        [ 3.1362e-01],
        [-1.3986e+00],
        [-1.4548e+00],
        [ 7.9733e-01],
        [ 6.3021e-01],
        [-1.7067e+00],
        [ 2.5929e-01],
        [-2.7541e-02],
        [ 3.6843e-01],
        [ 4.4334e-01],
        [ 8.4800e-01],
        [ 2.0323e+00],
        [-6.6591e-01],
        [-1.1390e+00],
        [ 6.2238e-01],
        [-1.4316e-01],
        [-1.2128e+00],
        [-3.7821e-01],
        [-1.1601e-01],
        [-3.7178e-04],
        [-8.6047e-01],
        [ 5.3561e-01],
        [ 1